In [8]:
import pandas

In [9]:
df = pandas.read_csv("eeg_features.csv")
df

ch0_mean    ch0_std   ch0_range  ch0_delta   ch0_theta  ch0_alpha  \
0    -27.587891  23.112185  120.605469        0.0   23.337409   6.534153   
1    -30.681610  24.948808  120.605469        0.0   98.608217  44.050490   
2    -32.772064  24.781974  120.605469        0.0  128.954611  75.076778   
3    -32.810211  24.753504  120.605469        0.0  101.903216  40.694791   
4    -32.657623  24.740149  120.605469        0.0  146.233400  61.910403   
...         ...        ...         ...        ...         ...        ...   
4077 -19.981384  16.545550  106.445312        0.0   28.231751  14.080412   
4078 -18.276215  14.118750   62.011719        0.0   36.192710  17.438050   
4079 -20.278931  14.925802   68.847656        0.0   41.496299  19.155415   
4080 -21.621704  14.496580   68.847656        0.0   47.626045  17.453870   
4081 -23.498535  14.539568   69.335938        0.0   43.354202  14.624134   

       ch0_beta  ch0_gamma  ch0_beta_alpha_ratio  ch0_theta_alpha_ratio  ...  \
0      5.660460   4.652484              0.866288               3.571604  ...   
1     11.981865   9.282773              0.272003               2.238527  ...   
2     13.218540  10.330687              0.176067               1.717636  ...   
3      8.218796   6.243245              0.201962               2.504085  ...   
4     13.376085  11.832481              0.216056               2.362017  ...   
...         ...        ...                   ...                    ...  ...   
4077  13.422488  20.430692              0.953274               2.005037  ...   
4078  18.795479  23.750285              1.077843               2.075502  ...   
4079  18.863969  11.615316              0.984785               2.166296  ...   
4080  16.897705  21.225989              0.968135               2.728681  ...   
4081  14.183944  32.851080              0.969900               2.964565  ...   

      ch4_std  ch4_range  ch4_delta  ch4_theta  ch4_alpha  ch4_beta  \
0         0.0        0.0        0.0        0.0        0.0       0.0   
1         0.0        0.0        0.0        0.0        0.0       0.0   
2         0.0        0.0        0.0        0.0        0.0       0.0   
3         0.0        0.0        0.0        0.0        0.0       0.0   
4         0.0        0.0        0.0        0.0        0.0       0.0   
...       ...        ...        ...        ...        ...       ...   
4077      0.0        0.0        0.0        0.0        0.0       0.0   
4078      0.0        0.0        0.0        0.0        0.0       0.0   
4079      0.0        0.0        0.0        0.0        0.0       0.0   
4080      0.0        0.0        0.0        0.0        0.0       0.0   
4081      0.0        0.0        0.0        0.0        0.0       0.0   

      ch4_gamma  ch4_beta_alpha_ratio  ch4_theta_alpha_ratio  label  
0           0.0                   0.0                    0.0    0.0  
1           0.0                   0.0                    0.0    0.0  
2           0.0                   0.0                    0.0    0.0  
3           0.0                   0.0                    0.0    0.0  
4           0.0                   0.0                    0.0    0.0  
...         ...                   ...                    ...    ...  
4077        0.0                   0.0                    0.0    3.0  
4078        0.0                   0.0                    0.0    3.0  
4079        0.0                   0.0                    0.0    3.0  
4080        0.0                   0.0                    0.0    3.0  
4081        0.0                   0.0                    0.0    3.0  

[4082 rows x 51 columns]

In [10]:
label_df = df[["label"]]
label_df

label
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
...     ...
4077    3.0
4078    3.0
4079    3.0
4080    3.0
4081    3.0

[4082 rows x 1 columns]

In [11]:
train_df = df.drop(columns=["label"])
train_df

ch0_mean    ch0_std   ch0_range  ch0_delta   ch0_theta  ch0_alpha  \
0    -27.587891  23.112185  120.605469        0.0   23.337409   6.534153   
1    -30.681610  24.948808  120.605469        0.0   98.608217  44.050490   
2    -32.772064  24.781974  120.605469        0.0  128.954611  75.076778   
3    -32.810211  24.753504  120.605469        0.0  101.903216  40.694791   
4    -32.657623  24.740149  120.605469        0.0  146.233400  61.910403   
...         ...        ...         ...        ...         ...        ...   
4077 -19.981384  16.545550  106.445312        0.0   28.231751  14.080412   
4078 -18.276215  14.118750   62.011719        0.0   36.192710  17.438050   
4079 -20.278931  14.925802   68.847656        0.0   41.496299  19.155415   
4080 -21.621704  14.496580   68.847656        0.0   47.626045  17.453870   
4081 -23.498535  14.539568   69.335938        0.0   43.354202  14.624134   

       ch0_beta  ch0_gamma  ch0_beta_alpha_ratio  ch0_theta_alpha_ratio  ...  \
0      5.660460   4.652484              0.866288               3.571604  ...   
1     11.981865   9.282773              0.272003               2.238527  ...   
2     13.218540  10.330687              0.176067               1.717636  ...   
3      8.218796   6.243245              0.201962               2.504085  ...   
4     13.376085  11.832481              0.216056               2.362017  ...   
...         ...        ...                   ...                    ...  ...   
4077  13.422488  20.430692              0.953274               2.005037  ...   
4078  18.795479  23.750285              1.077843               2.075502  ...   
4079  18.863969  11.615316              0.984785               2.166296  ...   
4080  16.897705  21.225989              0.968135               2.728681  ...   
4081  14.183944  32.851080              0.969900               2.964565  ...   

      ch4_mean  ch4_std  ch4_range  ch4_delta  ch4_theta  ch4_alpha  ch4_beta  \
0          0.0      0.0        0.0        0.0        0.0        0.0       0.0   
1          0.0      0.0        0.0        0.0        0.0        0.0       0.0   
2          0.0      0.0        0.0        0.0        0.0        0.0       0.0   
3          0.0      0.0        0.0        0.0        0.0        0.0       0.0   
4          0.0      0.0        0.0        0.0        0.0        0.0       0.0   
...        ...      ...        ...        ...        ...        ...       ...   
4077       0.0      0.0        0.0        0.0        0.0        0.0       0.0   
4078       0.0      0.0        0.0        0.0        0.0        0.0       0.0   
4079       0.0      0.0        0.0        0.0        0.0        0.0       0.0   
4080       0.0      0.0        0.0        0.0        0.0        0.0       0.0   
4081       0.0      0.0        0.0        0.0        0.0        0.0       0.0   

      ch4_gamma  ch4_beta_alpha_ratio  ch4_theta_alpha_ratio  
0           0.0                   0.0                    0.0  
1           0.0                   0.0                    0.0  
2           0.0                   0.0                    0.0  
3           0.0                   0.0                    0.0  
4           0.0                   0.0                    0.0  
...         ...                   ...                    ...  
4077        0.0                   0.0                    0.0  
4078        0.0                   0.0                    0.0  
4079        0.0                   0.0                    0.0  
4080        0.0                   0.0                    0.0  
4081        0.0                   0.0                    0.0  

[4082 rows x 50 columns]

In [12]:
training_data = train_df.values
label_data = label_df.values

training_data.shape, label_data.shape

((4082, 50), (4082, 1))

In [14]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import xgboost as xgb
import pickle

# Load your data
X_data = training_data
y_data = label_data

# Create DataFrame
columns = [f'eeg_{i}' for i in range(50)]
df = pd.DataFrame(X_data, columns=columns)
df['label'] = y_data.flatten() if y_data.ndim > 1 else y_data

# Separate features and target
X = df.drop('label', axis=1)
y = df['label']

print(f"Total samples: {len(X)}")
print(f"Original class distribution:\n{y.value_counts().sort_index()}\n")

# Balance dataset by undersampling majority classes
print("Balancing classes...")
class_counts = y.value_counts()
min_class_size = class_counts.min()

# Get indices for each class (0, 1, 2, 3)
class_indices = {cls: y[y == cls].index for cls in range(4)}

# Randomly sample min_class_size from each class
np.random.seed(42)
balanced_indices_list = []
for cls in range(4):
    sampled = np.random.choice(class_indices[cls], min_class_size, replace=False)
    balanced_indices_list.append(sampled)

# Combine and shuffle
balanced_indices = np.concatenate(balanced_indices_list)
np.random.shuffle(balanced_indices)

# Create balanced dataset
X_balanced = X.iloc[balanced_indices]
y_balanced = y.iloc[balanced_indices]

print(f"Balanced samples: {len(X_balanced)}")
print(f"Balanced class distribution:\n{y_balanced.value_counts().sort_index()}\n")

# Random 80/20 split with shuffle
X_train, X_test, y_train, y_test = train_test_split(
    X_balanced, y_balanced, test_size=0.2, random_state=42, shuffle=True, stratify=y_balanced
)

print(f"Training set: {len(X_train)}")
print(f"Test set: {len(X_test)}")
print(f"Training class distribution:\n{y_train.value_counts().sort_index()}")
print(f"Test class distribution:\n{y_test.value_counts().sort_index()}\n")

# Train XGBoost for multi-class classification
model = xgb.XGBClassifier(
    n_estimators=100,
    max_depth=3,  # Slightly increased for more complex patterns
    learning_rate=0.1,
    random_state=42,
    objective='multi:softmax',  # Multi-class classification
    num_class=4,  # 4 classes
    eval_metric='mlogloss'  # Multi-class log loss
)

print("Training model...")
model.fit(X_train, y_train)

# Predictions
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

# Results
train_acc = accuracy_score(y_train, y_pred_train)
test_acc = accuracy_score(y_test, y_pred_test)

print("\n" + "="*50)
print("RESULTS")
print("="*50)
print(f"Training Accuracy: {train_acc:.4f} ({train_acc*100:.2f}%)")
print(f"Test Accuracy: {test_acc:.4f} ({test_acc*100:.2f}%)")

print(f"\nConfusion Matrix:")
cm = confusion_matrix(y_test, y_pred_test)
print(cm)

# Pretty print confusion matrix
print("\nConfusion Matrix (formatted):")
print("Predicted →")
print("Actual ↓   ", end="")
for i in range(4):
    print(f"Class {i:>5}", end="  ")
print()
for i in range(4):
    print(f"Class {i}   ", end="")
    for j in range(4):
        print(f"{cm[i][j]:>7}", end="  ")
    print()

print(f"\nClassification Report:")
print(classification_report(y_test, y_pred_test, target_names=[f'Class {i}' for i in range(4)]))

# Feature importance
feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

print(f"\nTop 10 Features:")
print(feature_importance.head(10))

# Per-class accuracy
print("\nPer-Class Accuracy:")
for cls in range(4):
    mask = y_test == cls
    if mask.sum() > 0:
        cls_acc = accuracy_score(y_test[mask], y_pred_test[mask])
        print(f"  Class {cls}: {cls_acc:.4f} ({cls_acc*100:.2f}%)")

# Save model
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)
print(f"\n✓ Model saved to model.pkl")

Total samples: 4082
Original class distribution:
label
0.0    1024
1.0    1017
2.0    1005
3.0    1036
Name: count, dtype: int64

Balancing classes...
Balanced samples: 4020
Balanced class distribution:
label
0.0    1005
1.0    1005
2.0    1005
3.0    1005
Name: count, dtype: int64

Training set: 3216
Test set: 804
Training class distribution:
label
0.0    804
1.0    804
2.0    804
3.0    804
Name: count, dtype: int64
Test class distribution:
label
0.0    201
1.0    201
2.0    201
3.0    201
Name: count, dtype: int64

Training model...

RESULTS
Training Accuracy: 0.9966 (99.66%)
Test Accuracy: 0.9789 (97.89%)

Confusion Matrix:
[[196   3   1   1]
 [  4 195   0   2]
 [  2   0 198   1]
 [  1   1   1 198]]

Confusion Matrix (formatted):
Predicted →
Actual ↓   Class     0  Class     1  Class     2  Class     3  
Class 0       196        3        1        1  
Class 1         4      195        0        2  
Class 2         2        0      198        1  
Class 3         1        1        1    