In [1]:
import pandas

In [2]:
df = pandas.read_csv("eeg_features.csv")
df

ch0_mean    ch0_std   ch0_range  ch0_delta   ch0_theta  ch0_alpha  \
0   -36.190033  24.890195  144.531250        0.0  104.363895  34.566595   
1   -36.571503  22.140947  126.953125        0.0   17.387792   6.909083   
2   -33.248901  18.275259   92.773438        0.0   22.400267   8.083875   
3   -34.065247  17.239000   82.031250        0.0   26.498565  11.755329   
4   -37.490845  15.211344   69.824219        0.0   26.249210  17.963876   
..         ...        ...         ...        ...         ...        ...   
422 -42.659760  40.720371  234.863281        0.0   17.151528  26.029231   
423 -39.932251  39.925248  234.863281        0.0   18.936632  27.229536   
424 -29.911041  35.977325  234.863281        0.0   15.968942  14.671257   
425 -20.145416  29.243500  153.808594        0.0   10.818613  11.237438   
426  -5.493164  30.223559  159.667969        0.0  122.016649  48.103271   

       ch0_beta   ch0_gamma  ch0_beta_alpha_ratio  ch0_theta_alpha_ratio  ...  \
0     39.147497   73.976355              1.132524               3.019212  ...   
1     55.725362   72.931161              8.065522               2.516657  ...   
2     47.654234   70.093727              5.894974               2.770981  ...   
3     49.093623   48.334241              4.176287               2.254175  ...   
4     48.058497   21.728883              2.675285               1.461222  ...   
..          ...         ...                   ...                    ...  ...   
422  367.164804  334.179223             14.105864               0.658933  ...   
423  312.534478  276.440361             11.477774               0.695445  ...   
424  210.117485  215.060882             14.321710               1.088451  ...   
425  160.100115  133.836972             14.247030               0.962730  ...   
426   48.780005   74.469754              1.014068               2.536556  ...   

     ch4_std  ch4_range  ch4_delta  ch4_theta  ch4_alpha  ch4_beta  ch4_gamma  \
0        0.0        0.0        0.0        0.0        0.0       0.0        0.0   
1        0.0        0.0        0.0        0.0        0.0       0.0        0.0   
2        0.0        0.0        0.0        0.0        0.0       0.0        0.0   
3        0.0        0.0        0.0        0.0        0.0       0.0        0.0   
4        0.0        0.0        0.0        0.0        0.0       0.0        0.0   
..       ...        ...        ...        ...        ...       ...        ...   
422      0.0        0.0        0.0        0.0        0.0       0.0        0.0   
423      0.0        0.0        0.0        0.0        0.0       0.0        0.0   
424      0.0        0.0        0.0        0.0        0.0       0.0        0.0   
425      0.0        0.0        0.0        0.0        0.0       0.0        0.0   
426      0.0        0.0        0.0        0.0        0.0       0.0        0.0   

     ch4_beta_alpha_ratio  ch4_theta_alpha_ratio  label  
0                     0.0                    0.0    0.0  
1                     0.0                    0.0    0.0  
2                     0.0                    0.0    0.0  
3                     0.0                    0.0    0.0  
4                     0.0                    0.0    0.0  
..                    ...                    ...    ...  
422                   0.0                    0.0    3.0  
423                   0.0                    0.0    3.0  
424                   0.0                    0.0    3.0  
425                   0.0                    0.0    3.0  
426                   0.0                    0.0    3.0  

[427 rows x 51 columns]

In [3]:
label_df = df[["label"]]
label_df

label
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
..     ...
422    3.0
423    3.0
424    3.0
425    3.0
426    3.0

[427 rows x 1 columns]

In [5]:
train_df = df.drop(columns=["label"])
train_df

ch0_mean    ch0_std   ch0_range  ch0_delta   ch0_theta  ch0_alpha  \
0   -36.190033  24.890195  144.531250        0.0  104.363895  34.566595   
1   -36.571503  22.140947  126.953125        0.0   17.387792   6.909083   
2   -33.248901  18.275259   92.773438        0.0   22.400267   8.083875   
3   -34.065247  17.239000   82.031250        0.0   26.498565  11.755329   
4   -37.490845  15.211344   69.824219        0.0   26.249210  17.963876   
..         ...        ...         ...        ...         ...        ...   
422 -42.659760  40.720371  234.863281        0.0   17.151528  26.029231   
423 -39.932251  39.925248  234.863281        0.0   18.936632  27.229536   
424 -29.911041  35.977325  234.863281        0.0   15.968942  14.671257   
425 -20.145416  29.243500  153.808594        0.0   10.818613  11.237438   
426  -5.493164  30.223559  159.667969        0.0  122.016649  48.103271   

       ch0_beta   ch0_gamma  ch0_beta_alpha_ratio  ch0_theta_alpha_ratio  ...  \
0     39.147497   73.976355              1.132524               3.019212  ...   
1     55.725362   72.931161              8.065522               2.516657  ...   
2     47.654234   70.093727              5.894974               2.770981  ...   
3     49.093623   48.334241              4.176287               2.254175  ...   
4     48.058497   21.728883              2.675285               1.461222  ...   
..          ...         ...                   ...                    ...  ...   
422  367.164804  334.179223             14.105864               0.658933  ...   
423  312.534478  276.440361             11.477774               0.695445  ...   
424  210.117485  215.060882             14.321710               1.088451  ...   
425  160.100115  133.836972             14.247030               0.962730  ...   
426   48.780005   74.469754              1.014068               2.536556  ...   

     ch4_mean  ch4_std  ch4_range  ch4_delta  ch4_theta  ch4_alpha  ch4_beta  \
0         0.0      0.0        0.0        0.0        0.0        0.0       0.0   
1         0.0      0.0        0.0        0.0        0.0        0.0       0.0   
2         0.0      0.0        0.0        0.0        0.0        0.0       0.0   
3         0.0      0.0        0.0        0.0        0.0        0.0       0.0   
4         0.0      0.0        0.0        0.0        0.0        0.0       0.0   
..        ...      ...        ...        ...        ...        ...       ...   
422       0.0      0.0        0.0        0.0        0.0        0.0       0.0   
423       0.0      0.0        0.0        0.0        0.0        0.0       0.0   
424       0.0      0.0        0.0        0.0        0.0        0.0       0.0   
425       0.0      0.0        0.0        0.0        0.0        0.0       0.0   
426       0.0      0.0        0.0        0.0        0.0        0.0       0.0   

     ch4_gamma  ch4_beta_alpha_ratio  ch4_theta_alpha_ratio  
0          0.0                   0.0                    0.0  
1          0.0                   0.0                    0.0  
2          0.0                   0.0                    0.0  
3          0.0                   0.0                    0.0  
4          0.0                   0.0                    0.0  
..         ...                   ...                    ...  
422        0.0                   0.0                    0.0  
423        0.0                   0.0                    0.0  
424        0.0                   0.0                    0.0  
425        0.0                   0.0                    0.0  
426        0.0                   0.0                    0.0  

[427 rows x 50 columns]

In [6]:
training_data = train_df.values
label_data = label_df.values

training_data.shape, label_data.shape

((427, 50), (427, 1))

In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import xgboost as xgb
import pickle

# Load your data
X_data = training_data
y_data = label_data

# Create DataFrame
columns = [f'eeg_{i}' for i in range(50)]
df = pd.DataFrame(X_data, columns=columns)
df['label'] = y_data.flatten() if y_data.ndim > 1 else y_data

# Separate features and target
X = df.drop('label', axis=1)
y = df['label']

print(f"Total samples: {len(X)}")
print(f"Original class distribution:\n{y.value_counts().sort_index()}\n")

# Balance dataset by undersampling majority classes
print("Balancing classes...")
class_counts = y.value_counts()
min_class_size = class_counts.min()

# Get indices for each class (0, 1, 2, 3)
class_indices = {cls: y[y == cls].index for cls in range(4)}

# Randomly sample min_class_size from each class
np.random.seed(42)
balanced_indices_list = []
for cls in range(4):
    sampled = np.random.choice(class_indices[cls], min_class_size, replace=False)
    balanced_indices_list.append(sampled)

# Combine and shuffle
balanced_indices = np.concatenate(balanced_indices_list)
np.random.shuffle(balanced_indices)

# Create balanced dataset
X_balanced = X.iloc[balanced_indices]
y_balanced = y.iloc[balanced_indices]

print(f"Balanced samples: {len(X_balanced)}")
print(f"Balanced class distribution:\n{y_balanced.value_counts().sort_index()}\n")

# Random 80/20 split with shuffle
X_train, X_test, y_train, y_test = train_test_split(
    X_balanced, y_balanced, test_size=0.2, random_state=42, shuffle=True, stratify=y_balanced
)

print(f"Training set: {len(X_train)}")
print(f"Test set: {len(X_test)}")
print(f"Training class distribution:\n{y_train.value_counts().sort_index()}")
print(f"Test class distribution:\n{y_test.value_counts().sort_index()}\n")

# Train XGBoost for multi-class classification
model = xgb.XGBClassifier(
    n_estimators=100,
    max_depth=3,  # Slightly increased for more complex patterns
    learning_rate=0.1,
    random_state=42,
    objective='multi:softmax',  # Multi-class classification
    num_class=4,  # 4 classes
    eval_metric='mlogloss'  # Multi-class log loss
)

print("Training model...")
model.fit(X_train, y_train)

# Predictions
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

# Results
train_acc = accuracy_score(y_train, y_pred_train)
test_acc = accuracy_score(y_test, y_pred_test)

print("\n" + "="*50)
print("RESULTS")
print("="*50)
print(f"Training Accuracy: {train_acc:.4f} ({train_acc*100:.2f}%)")
print(f"Test Accuracy: {test_acc:.4f} ({test_acc*100:.2f}%)")

print(f"\nConfusion Matrix:")
cm = confusion_matrix(y_test, y_pred_test)
print(cm)

# Pretty print confusion matrix
print("\nConfusion Matrix (formatted):")
print("Predicted →")
print("Actual ↓   ", end="")
for i in range(4):
    print(f"Class {i:>5}", end="  ")
print()
for i in range(4):
    print(f"Class {i}   ", end="")
    for j in range(4):
        print(f"{cm[i][j]:>7}", end="  ")
    print()

print(f"\nClassification Report:")
print(classification_report(y_test, y_pred_test, target_names=[f'Class {i}' for i in range(4)]))

# Feature importance
feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

print(f"\nTop 10 Features:")
print(feature_importance.head(10))

# Per-class accuracy
print("\nPer-Class Accuracy:")
for cls in range(4):
    mask = y_test == cls
    if mask.sum() > 0:
        cls_acc = accuracy_score(y_test[mask], y_pred_test[mask])
        print(f"  Class {cls}: {cls_acc:.4f} ({cls_acc*100:.2f}%)")

# Save model
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)
print(f"\n✓ Model saved to model.pkl")

Total samples: 427
Original class distribution:
label
0.0    106
1.0    108
2.0    101
3.0    112
Name: count, dtype: int64

Balancing classes...
Balanced samples: 404
Balanced class distribution:
label
0.0    101
1.0    101
2.0    101
3.0    101
Name: count, dtype: int64

Training set: 323
Test set: 81
Training class distribution:
label
0.0    81
1.0    81
2.0    80
3.0    81
Name: count, dtype: int64
Test class distribution:
label
0.0    20
1.0    20
2.0    21
3.0    20
Name: count, dtype: int64

Training model...

RESULTS
Training Accuracy: 1.0000 (100.00%)
Test Accuracy: 0.9753 (97.53%)

Confusion Matrix:
[[20  0  0  0]
 [ 0 20  0  0]
 [ 0  0 21  0]
 [ 0  2  0 18]]

Confusion Matrix (formatted):
Predicted →
Actual ↓   Class     0  Class     1  Class     2  Class     3  
Class 0        20        0        0        0  
Class 1         0       20        0        0  
Class 2         0        0       21        0  
Class 3         0        2        0       18  

Classification Report:
   